//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace MyWindowsService.Qz {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DcipserviceSoap11Binding", Namespace="http://service.communication.service.dareway.com")]
    public partial class Dcipservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback userTransApplicationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Dcipservice() {
            this.Url = global::MyWindowsService.Properties.Settings.Default.MyWindowsService_Qz_Dcipservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event userTransApplicationCompletedEventHandler userTransApplicationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:userTransApplication", RequestNamespace="http://serviceproxy.dareway.com", ResponseNamespace="http://serviceproxy.dareway.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string userTransApplication([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string method, double jylsh, [System.Xml.Serialization.XmlIgnoreAttribute()] bool jylshSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string inParameters, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string outParameters, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ydbm, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string model) {
            object[] results = this.Invoke("userTransApplication", new object[] {
                        method,
                        jylsh,
                        jylshSpecified,
                        inParameters,
                        outParameters,
                        ydbm,
                        model});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void userTransApplicationAsync(string method, double jylsh, bool jylshSpecified, string inParameters, string outParameters, string ydbm, string model) {
            this.userTransApplicationAsync(method, jylsh, jylshSpecified, inParameters, outParameters, ydbm, model, null);
        }
        
        /// <remarks/>
        public void userTransApplicationAsync(string method, double jylsh, bool jylshSpecified, string inParameters, string outParameters, string ydbm, string model, object userState) {
            if ((this.userTransApplicationOperationCompleted == null)) {
                this.userTransApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuserTransApplicationOperationCompleted);
            }
            this.InvokeAsync("userTransApplication", new object[] {
                        method,
                        jylsh,
                        jylshSpecified,
                        inParameters,
                        outParameters,
                        ydbm,
                        model}, this.userTransApplicationOperationCompleted, userState);
        }
        
        private void OnuserTransApplicationOperationCompleted(object arg) {
            if ((this.userTransApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.userTransApplicationCompleted(this, new userTransApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void userTransApplicationCompletedEventHandler(object sender, userTransApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class userTransApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal userTransApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591